.TH CD-DISCID 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
cd-discid \- read CD and get CDDB discid information.
.SH SYNOPSIS
.B cd-discid
[--musicbrainz]
.I [devicename]
.SH "DESCRIPTION"
In order to do CDDB queries over the Internet, you must know the DiscID of
the CD you are querying.
.BR cd-discid
provides you with that information. It outputs the discid, the number of
tracks, the frame offset of all of the tracks, and the total length of the
CD in seconds, on one line in a space-delimited format.
.BR cd-discid
was designed as a backend tool for cdgrab (now
.BR abcde )
but will work independently of it.
.SH OPTIONS
.TP
.B --musicbrainz
Output a TOC that is suitable for calculating the MusicBrainz disc id.
.TP
.B devicename
CD\-ROM block device name that contains the CD to be queried. If this option
is omitted, the following device name is assumed:
.RS
.IP \fI/dev/cdrom\fP
for Linux and FreeBSD
.IP \fI/dev/cd0a\fP
for OpenBSD and NetBSD
.IP \fI/dev/vol/aliases/cdrom0\fP
for Solaris
.IP \fI/dev/disk1\fP
for MacOS X
.SH AUTHOR
Robert Woodcock <rcw@debian.org>. Updates by Timur Bish <taem@linukz.org>
